// This file is automatically generated. Do not edit by hand.

import Foundation

struct LocaleKey: RawRepresentable {
  let rawValue: String

  init(rawValue: String) {
    self.rawValue = rawValue
  }

  init(_ rawValue: String) {
    self.rawValue = rawValue
  }
}

extension LocaleKey {
  func tr() -> String {
    AppLocale.shared.localizedString(rawValue)
  }

  func tr(_ args: CVarArg...) -> String {
    var template = tr()
    for _ in args {
      template = template.replacingOccurrences(
        of: "{}", with: "%@", options: [], range: template.range(of: "{}"))
    }
    return String(format: template, locale: Locale.current, arguments: args)
  }
}

enum LocaleKeys {
  enum app {
    enum tray {
      enum contextMenu {
        static let checkForUpdates = LocaleKey("app.tray.context_menu.check_for_updates")
        enum devTools {
          static let openDataDirectory = LocaleKey(
            "app.tray.context_menu.dev_tools.open_data_directory")
          static let title = LocaleKey("app.tray.context_menu.dev_tools.title")
          static let useNativeSettings = LocaleKey(
            "app.tray.context_menu.dev_tools.use_native_settings")
        }
        static let quit = LocaleKey("app.tray.context_menu.quit")
        static let settings = LocaleKey("app.tray.context_menu.settings")
        static let showWindow = LocaleKey("app.tray.context_menu.show_window")
      }
    }
  }
  enum common {
    enum language {
      static let ar = LocaleKey("common.language.ar")
      static let bn = LocaleKey("common.language.bn")
      static let de = LocaleKey("common.language.de")
      static let en = LocaleKey("common.language.en")
      static let es = LocaleKey("common.language.es")
      static let fa = LocaleKey("common.language.fa")
      static let fr = LocaleKey("common.language.fr")
      static let gu = LocaleKey("common.language.gu")
      static let ha = LocaleKey("common.language.ha")
      static let hi = LocaleKey("common.language.hi")
      static let id = LocaleKey("common.language.id")
      static let it = LocaleKey("common.language.it")
      static let ja = LocaleKey("common.language.ja")
      static let jv = LocaleKey("common.language.jv")
      static let ko = LocaleKey("common.language.ko")
      static let ml = LocaleKey("common.language.ml")
      static let mr = LocaleKey("common.language.mr")
      static let ms = LocaleKey("common.language.ms")
      static let nl = LocaleKey("common.language.nl")
      static let pa = LocaleKey("common.language.pa")
      static let pl = LocaleKey("common.language.pl")
      static let pt = LocaleKey("common.language.pt")
      static let ro = LocaleKey("common.language.ro")
      static let ru = LocaleKey("common.language.ru")
      static let sw = LocaleKey("common.language.sw")
      static let ta = LocaleKey("common.language.ta")
      static let te = LocaleKey("common.language.te")
      static let th = LocaleKey("common.language.th")
      static let tr = LocaleKey("common.language.tr")
      static let uk = LocaleKey("common.language.uk")
      static let ur = LocaleKey("common.language.ur")
      static let vi = LocaleKey("common.language.vi")
      static let yo = LocaleKey("common.language.yo")
      static let zhHans = LocaleKey("common.language.zh_hans")
      static let zhHant = LocaleKey("common.language.zh_hant")
    }
    enum provider {
      static let anthropic = LocaleKey("common.provider.anthropic")
      static let baidu = LocaleKey("common.provider.baidu")
      static let caiyun = LocaleKey("common.provider.caiyun")
      static let deepl = LocaleKey("common.provider.deepl")
      static let google = LocaleKey("common.provider.google")
      static let ollama = LocaleKey("common.provider.ollama")
      static let openai = LocaleKey("common.provider.openai")
      static let sogou = LocaleKey("common.provider.sogou")
      static let system = LocaleKey("common.provider.system")
      static let tencent = LocaleKey("common.provider.tencent")
      static let xai = LocaleKey("common.provider.xai")
      static let youdao = LocaleKey("common.provider.youdao")
    }
    enum themeMode {
      static let dark = LocaleKey("common.theme_mode.dark")
      static let light = LocaleKey("common.theme_mode.light")
      static let system = LocaleKey("common.theme_mode.system")
    }
    enum ui {
      enum button {
        static let add = LocaleKey("common.ui.button.add")
        static let cancel = LocaleKey("common.ui.button.cancel")
        static let `continue` = LocaleKey("common.ui.button.continue")
        static let delete = LocaleKey("common.ui.button.delete")
        static let edit = LocaleKey("common.ui.button.edit")
        static let manage = LocaleKey("common.ui.button.manage")
        static let ok = LocaleKey("common.ui.button.ok")
        static let save = LocaleKey("common.ui.button.save")
      }
      enum feedback {
        static let copied = LocaleKey("common.ui.feedback.copied")
      }
    }
    enum wordPronunciation {
      static let uk = LocaleKey("common.word_pronunciation.uk")
      static let us = LocaleKey("common.word_pronunciation.us")
    }
  }
  enum miniTranslator {
    enum button {
      static let clear = LocaleKey("mini_translator.button.clear")
      static let translate = LocaleKey("mini_translator.button.translate")
    }
    enum input {
      static let extractingText = LocaleKey("mini_translator.input.extracting_text")
      static let hint = LocaleKey("mini_translator.input.hint")
    }
    enum language {
      static let addTarget = LocaleKey("mini_translator.language.add_target")
      static let autoDetect = LocaleKey("mini_translator.language.auto_detect")
      static let autoMatch = LocaleKey("mini_translator.language.auto_match")
      static let manageCommonLanguages = LocaleKey(
        "mini_translator.language.manage_common_languages")
      static let manageTargets = LocaleKey("mini_translator.language.manage_targets")
      static let moreLanguages = LocaleKey("mini_translator.language.more_languages")
      static let switchConfig = LocaleKey("mini_translator.language.switch_config")
    }
    enum limitedBanner {
      enum action {
        static let appSettings = LocaleKey("mini_translator.limited_banner.action.app_settings")
        static let recheck = LocaleKey("mini_translator.limited_banner.action.recheck")
      }
      enum feedback {
        static let enabled = LocaleKey("mini_translator.limited_banner.feedback.enabled")
        static let stillMissing = LocaleKey("mini_translator.limited_banner.feedback.still_missing")
      }
      enum instruction {
        static let appSettingsPrefix = LocaleKey(
          "mini_translator.limited_banner.instruction.app_settings_prefix")
        static let followGuidePrefix = LocaleKey(
          "mini_translator.limited_banner.instruction.follow_guide_prefix")
        static let suffix = LocaleKey("mini_translator.limited_banner.instruction.suffix")
      }
      enum permission {
        static let missingAccessibility = LocaleKey(
          "mini_translator.limited_banner.permission.missing_accessibility")
        static let missingBoth = LocaleKey("mini_translator.limited_banner.permission.missing_both")
        static let missingScreenCapture = LocaleKey(
          "mini_translator.limited_banner.permission.missing_screen_capture")
      }
      enum tooltip {
        static let help = LocaleKey("mini_translator.limited_banner.tooltip.help")
      }
    }
    enum message {
      static let captureScreenAreaCanceled = LocaleKey(
        "mini_translator.message.capture_screen_area_canceled")
      static let ocrRecognitionFailed = LocaleKey("mini_translator.message.ocr_recognition_failed")
      static let ocrServiceNotConfigured = LocaleKey(
        "mini_translator.message.ocr_service_not_configured")
      static let pleaseEnterWordOrText = LocaleKey(
        "mini_translator.message.please_enter_word_or_text")
    }
    enum toolbar {
      enum tooltip {
        static let extractTextFromClipboard = LocaleKey(
          "mini_translator.toolbar.tooltip.extract_text_from_clipboard")
        static let extractTextFromScreenCapture = LocaleKey(
          "mini_translator.toolbar.tooltip.extract_text_from_screen_capture")
      }
    }
  }
  enum settings {
    enum about {
      static let checkAgain = LocaleKey("settings.about.check_again")
      static let copyVersionInfo = LocaleKey("settings.about.copy_version_info")
      static let github = LocaleKey("settings.about.github")
      static let license = LocaleKey("settings.about.license")
      static let links = LocaleKey("settings.about.links")
      static let openChangelog = LocaleKey("settings.about.open_changelog")
      static let reportIssue = LocaleKey("settings.about.report_issue")
      static let title = LocaleKey("settings.about.title")
      static let upToDate = LocaleKey("settings.about.up_to_date")
      static let website = LocaleKey("settings.about.website")
    }
    enum advanced {
      static let apiServer = LocaleKey("settings.advanced.api_server")
      static let apiServerDescription = LocaleKey("settings.advanced.api_server_description")
      static let disabled = LocaleKey("settings.advanced.disabled")
      static let enable = LocaleKey("settings.advanced.enable")
      static let port = LocaleKey("settings.advanced.port")
      static let runningAt = LocaleKey("settings.advanced.running_at")
      static let title = LocaleKey("settings.advanced.title")
    }
    enum appearance {
      enum section {
        static let appLanguage = LocaleKey("settings.appearance.section.app_language")
        static let themeMode = LocaleKey("settings.appearance.section.theme_mode")
      }
      static let title = LocaleKey("settings.appearance.title")
    }
    enum general {
      enum button {
        static let addProvider = LocaleKey("settings.general.button.add_provider")
        static let addTarget = LocaleKey("settings.general.button.add_target")
        static let grant = LocaleKey("settings.general.button.grant")
        static let manageLanguages = LocaleKey("settings.general.button.manage_languages")
        static let manageTargets = LocaleKey("settings.general.button.manage_targets")
      }
      enum editor {
        static let addTargetTitle = LocaleKey("settings.general.editor.add_target_title")
        static let editTargetTitle = LocaleKey("settings.general.editor.edit_target_title")
        enum row {
          static let sourceLanguage = LocaleKey("settings.general.editor.row.source_language")
          static let targetLanguage = LocaleKey("settings.general.editor.row.target_language")
        }
      }
      enum option {
        static let builtInOcr = LocaleKey("settings.general.option.built_in_ocr")
        static let granted = LocaleKey("settings.general.option.granted")
        static let noServicesAvailable = LocaleKey("settings.general.option.no_services_available")
        static let none = LocaleKey("settings.general.option.none")
        static let tesseract = LocaleKey("settings.general.option.tesseract")
        static let youdaoOcr = LocaleKey("settings.general.option.youdao_ocr")
      }
      enum row {
        static let autoCopyDetectedText = LocaleKey("settings.general.row.auto_copy_detected_text")
        static let commonLanguages = LocaleKey("settings.general.row.common_languages")
        static let commonLanguagesAll = LocaleKey("settings.general.row.common_languages_all")
        static let commonLanguagesDescription = LocaleKey(
          "settings.general.row.common_languages_description")
        static let commonLanguagesHint = LocaleKey("settings.general.row.common_languages_hint")
        static let commonLanguagesReset = LocaleKey("settings.general.row.common_languages_reset")
        static let commonLanguagesResetHelp = LocaleKey(
          "settings.general.row.common_languages_reset_help")
        static let commonLanguagesSearch = LocaleKey("settings.general.row.common_languages_search")
        static let commonLanguagesSort = LocaleKey("settings.general.row.common_languages_sort")
        static let defaultDirectoryService = LocaleKey(
          "settings.general.row.default_directory_service")
        static let defaultOcrService = LocaleKey("settings.general.row.default_ocr_service")
        static let defaultTranslationService = LocaleKey(
          "settings.general.row.default_translation_service")
        static let doubleClickCopyResult = LocaleKey(
          "settings.general.row.double_click_copy_result")
        static let launchAtLogin = LocaleKey("settings.general.row.launch_at_login")
        static let screenCaptureAccess = LocaleKey("settings.general.row.screen_capture_access")
        static let screenSelectionAccess = LocaleKey("settings.general.row.screen_selection_access")
        static let showInMenuBar = LocaleKey("settings.general.row.show_in_menu_bar")
        static let submitWithEnter = LocaleKey("settings.general.row.submit_with_enter")
        static let submitWithMetaEnterMac = LocaleKey(
          "settings.general.row.submit_with_meta_enter_mac")
        static let translationTargetHint = LocaleKey("settings.general.row.translation_target_hint")
      }
      enum section {
        static let directory = LocaleKey("settings.general.section.directory")
        static let input = LocaleKey("settings.general.section.input")
        static let languages = LocaleKey("settings.general.section.languages")
        static let ocr = LocaleKey("settings.general.section.ocr")
        static let permissions = LocaleKey("settings.general.section.permissions")
        static let translation = LocaleKey("settings.general.section.translation")
        static let translationTarget = LocaleKey("settings.general.section.translation_target")
      }
      static let title = LocaleKey("settings.general.title")
    }
    enum layout {
      enum empty {
        static let message = LocaleKey("settings.layout.empty.message")
        static let title = LocaleKey("settings.layout.empty.title")
      }
      static let title = LocaleKey("settings.layout.title")
    }
    enum providers {
      enum alert {
        static let error = LocaleKey("settings.providers.alert.error")
      }
      enum button {
        static let add = LocaleKey("settings.providers.button.add")
      }
      enum capability {
        static let dictionary = LocaleKey("settings.providers.capability.dictionary")
        static let ocr = LocaleKey("settings.providers.capability.ocr")
        static let translation = LocaleKey("settings.providers.capability.translation")
      }
      enum deleteDialog {
        static let message = LocaleKey("settings.providers.delete_dialog.message")
        static let title = LocaleKey("settings.providers.delete_dialog.title")
      }
      enum description {
        static let all = LocaleKey("settings.providers.description.all")
        static let dictionary = LocaleKey("settings.providers.description.dictionary")
        static let fallback = LocaleKey("settings.providers.description.fallback")
        static let translation = LocaleKey("settings.providers.description.translation")
      }
      enum detail {
        enum models {
          static let defaultBadge = LocaleKey("settings.providers.detail.models.default_badge")
          static let empty = LocaleKey("settings.providers.detail.models.empty")
          static let fetchError = LocaleKey("settings.providers.detail.models.fetch_error")
          static let loading = LocaleKey("settings.providers.detail.models.loading")
          static let retry = LocaleKey("settings.providers.detail.models.retry")
        }
        enum section {
          static let configuration = LocaleKey("settings.providers.detail.section.configuration")
          static let models = LocaleKey("settings.providers.detail.section.models")
        }
        enum tooltip {
          static let edit = LocaleKey("settings.providers.detail.tooltip.edit")
        }
      }
      enum editor {
        enum placeholder {
          static let id = LocaleKey("settings.providers.editor.placeholder.id")
        }
        enum row {
          static let id = LocaleKey("settings.providers.editor.row.id")
        }
        enum tooltip {
          static let help = LocaleKey("settings.providers.editor.tooltip.help")
        }
        enum typePicker {
          static let prompt = LocaleKey("settings.providers.editor.type_picker.prompt")
          static let sectionLlm = LocaleKey("settings.providers.editor.type_picker.section_llm")
          static let sectionTraditional = LocaleKey(
            "settings.providers.editor.type_picker.section_traditional")
        }
      }
      enum intro {
        static let body = LocaleKey("settings.providers.intro.body")
        static let warning = LocaleKey("settings.providers.intro.warning")
      }
      enum item {
        static let empty = LocaleKey("settings.providers.item.empty")
        static let loading = LocaleKey("settings.providers.item.loading")
        static let noServices = LocaleKey("settings.providers.item.no_services")
      }
      enum section {
        static let services = LocaleKey("settings.providers.section.services")
        static let servicesDescription = LocaleKey(
          "settings.providers.section.services_description")
      }
      static let title = LocaleKey("settings.providers.title")
    }
    enum services {
      enum button {
        static let addService = LocaleKey("settings.services.button.add_service")
      }
      enum detail {
        enum deleteDialog {
          static let message = LocaleKey("settings.services.detail.delete_dialog.message")
          static let title = LocaleKey("settings.services.detail.delete_dialog.title")
        }
        static let promptVariables = LocaleKey("settings.services.detail.prompt_variables")
        enum row {
          static let name = LocaleKey("settings.services.detail.row.name")
          static let provider = LocaleKey("settings.services.detail.row.provider")
          static let type = LocaleKey("settings.services.detail.row.type")
        }
      }
      enum editor {
        static let comingSoon = LocaleKey("settings.services.editor.coming_soon")
        static let comingSoonDescription = LocaleKey(
          "settings.services.editor.coming_soon_description")
      }
      enum section {
        static let availableServices = LocaleKey("settings.services.section.available_services")
      }
      static let title = LocaleKey("settings.services.title")
    }
    enum shortcuts {
      enum resetDialog {
        static let cancel = LocaleKey("settings.shortcuts.reset_dialog.cancel")
        static let confirm = LocaleKey("settings.shortcuts.reset_dialog.confirm")
        static let message = LocaleKey("settings.shortcuts.reset_dialog.message")
        static let title = LocaleKey("settings.shortcuts.reset_dialog.title")
      }
      enum row {
        static let extractTextFromClipboard = LocaleKey(
          "settings.shortcuts.row.extract_text_from_clipboard")
        static let extractTextFromScreenCapture = LocaleKey(
          "settings.shortcuts.row.extract_text_from_screen_capture")
        static let extractTextFromScreenSelection = LocaleKey(
          "settings.shortcuts.row.extract_text_from_screen_selection")
        static let toggleMiniTranslator = LocaleKey("settings.shortcuts.row.toggle_mini_translator")
        static let translateInput = LocaleKey("settings.shortcuts.row.translate_input")
      }
      enum section {
        static let inputAssist = LocaleKey("settings.shortcuts.section.input_assist")
        static let textExtraction = LocaleKey("settings.shortcuts.section.text_extraction")
      }
      static let title = LocaleKey("settings.shortcuts.title")
    }
    static let version = LocaleKey("settings.version")
  }
}
