name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "dc2a8703e12bda92ae379f291d757c361f3069a3"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run analyze

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "dc2a8703e12bda92ae379f291d757c361f3069a3"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run format-check

  dependency_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "dc2a8703e12bda92ae379f291d757c361f3069a3"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run dependency_validator
