name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "c8c5e3bd7542962ee8b09a12ac469d7d1ff823e0"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run analyze

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "c8c5e3bd7542962ee8b09a12ac469d7d1ff823e0"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run format-check

  dependency_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
          flutter-version: "c8c5e3bd7542962ee8b09a12ac469d7d1ff823e0"
          cache: true
      - uses: bluefireteam/melos-action@v2
      - run: melos run dependency_validator
